server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: false
  error:
    include-message: always
    whitelabel:
      enabled: true
  tomcat:
    max-swallow-size: 100MB
    accept-count: 1024
    max-connections: 32768
    threads:
      max: 512
    max-keep-alive-requests: 4096
    keep-alive-timeout: 300s
    connection-timeout: 300s
  undertow:
    allow-encoded-slash: false
    always-set-keep-alive: true
    max-cookies: 200
    max-headers: 12
    max-parameters: 20
    url-charset: UTF-8

spring:
  main:
    allow-circular-references: true
    banner-mode: off
    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jmx:
    enabled: false
  jackson:
    time-zone: UTC

  mvc:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    pathmatch:
      matching-strategy: ant_path_matcher
    async:
      request-timeout: 3600000

  cache:
    jcache:
      config: classpath:ehcache.xml

  flyway:
    baseline-on-migrate: true

  security:
    session:
      concurrent: true
    bruteforce:
      login_retries: 5
      lock_period:
        seconds: 300
    login_pass:
      enabled: false

  mail:
      default-encoding: UTF-8
      host: ${MAIL_HOST}
      port: ${MAIL_PORT}
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      protocol: ${MAIL_PROTOCOL}
      properties:
        mail:
          smtp:
            username: ${MAIL_USERNAME}
            password: ${MAIL_PASSWORD}
            host: ${MAIL_HOST}
            port: ${MAIL_PORT}
            auth: true
            writetimeout: 10000
            connectiontimeout: 10000
            timeout: 10000
            ssl:
              trust: ${MAIL_SSL_TRUST}
              enable: true
            starttls:
              enable: true
              required: true
      test-connection: true

  # Database
  datasource:
    platform: postgres
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          order_inserts: true
          order_updates: true
          jdbc:
            batch_size: 1000
            lob:
              non_contextual_creation: true
          time_zone: UTC
          event:
            merge:
              entity_copy_observer: allow
          format_sql: true
          open-in-view: false
        hikari:
          maximum-pool-size: 1000
          minimum-idle: 5
          idle-timeout: 60000
          connection-timeout: 120000

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}

# Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org:hibernate.SQL: debug
    org.springframework.ws: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: debug


# Files
file:
  folder: ${FILES_STORAGE_PATH}
  max-size: 1073741824

# JWT
jwt:
  expiration: 86400000
  refresh-token:
    expiration: 604800000000

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_ACCESS_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}
  client:
    url: ${CLIENT_URL}
  server:
    url: ${SERVER_URL}


integrations:
  spotify:
    client:
      id: ${SPOTIFY_CLIENT_ID}
      secret: ${SPOTIFY_CLIENT_SECRET}
    redirect-url: ${SPOTIFY_REDIRECT_URL}